name: publish

on: [push]

env:
  TAG: 8.0.6

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}

    - name: Build the hello-world Docker image
      run: |
        docker build . -t ghcr.io/${{ github.repository }}:$TAG
        docker push ghcr.io/${{ github.repository }}:$TAG
